"""Initial revision

Revision ID: 3060be8993df
Revises: 
Create Date: 2022-01-18 00:02:01.742090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3060be8993df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_id'), ['id'], unique=False)

    op.create_table('unit',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('condo_name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unit_id'), ['id'], unique=False)

    op.create_table('unit_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type_expense', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('payment_status', sa.String(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], name='fk_unit_unit_expenses'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('unit_expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unit_expenses_id'), ['id'], unique=False)

    op.create_table('unit_tenant',
    sa.Column('unit_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name='fk_tenant'),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], name='fk_unit'),
    sa.PrimaryKeyConstraint('unit_id', 'tenant_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unit_tenant')
    with op.batch_alter_table('unit_expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unit_expenses_id'))

    op.drop_table('unit_expenses')
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unit_id'))

    op.drop_table('unit')
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_id'))

    op.drop_table('tenant')
    # ### end Alembic commands ###
